const ANIMATIONS = {
  playerRunRight: 1,
  playerRunLeft: 2,
  playerLadderClimbUp: 3,
  playerLadderClimbDown: 4,
  playerRopeClimbLeft: 5,
  playerRopeClimbRight: 6,
  enemyRunRight: 7,
  enemyRunLeft: 8,
  enemyLadderClimbUp: 9,
  enemyLadderClimbDown: 10,
  enemyRopeClimbLeft: 11,
  enemyRopeClimbRight: 12,
  brickDig: 13,
  brickRecovery: 14,
};

const ANIMATIONS_CONFIG = {
  [ANIMATIONS.playerRunRight]: {
    path: 'player',
    fileName: 'player_run_right',
    name: [ANIMATIONS.playerRunRight],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.playerRunLeft]: {
    path: 'player',
    fileName: 'player_run_left',
    name: [ANIMATIONS.playerRunLeft],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.playerLadderClimbUp]: {
    path: 'player',
    fileName: 'player_ladder_climb',
    name: [ANIMATIONS.playerLadderClimbUp],
    end: 2,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.playerLadderClimbDown]: {
    path: 'player',
    fileName: 'player_ladder_climb',
    name: [ANIMATIONS.playerLadderClimbDown],
    end: 2,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.playerRopeClimbLeft]: {
    path: 'player',
    fileName: 'player_rope_climb_left',
    name: [ANIMATIONS.playerRopeClimbLeft],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.playerRopeClimbRight]: {
    path: 'player',
    fileName: 'player_rope_climb_right',
    name: [ANIMATIONS.playerRopeClimbRight],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.enemyRunRight]: {
    path: 'enemy',
    fileName: 'enemy_run_right',
    name: [ANIMATIONS.enemyRunRight],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.enemyRunLeft]: {
    path: 'enemy',
    fileName: 'enemy_run_left',
    name: [ANIMATIONS.enemyRunLeft],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.enemyLadderClimbUp]: {
    path: 'enemy',
    fileName: 'enemy_ladder_climb',
    name: [ANIMATIONS.enemyLadderClimbUp],
    end: 2,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.enemyLadderClimbDown]: {
    path: 'enemy',
    fileName: 'enemy_ladder_climb',
    name: [ANIMATIONS.enemyLadderClimbDown],
    end: 2,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.enemyRopeClimbLeft]: {
    path: 'enemy',
    fileName: 'enemy_rope_climb_left',
    name: [ANIMATIONS.enemyRopeClimbLeft],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.enemyRopeClimbRight]: {
    path: 'enemy',
    fileName: 'enemy_rope_climb_right',
    name: [ANIMATIONS.enemyRopeClimbRight],
    end: 3,
    loop: true,
    frameRate: 15,
  },
  [ANIMATIONS.brickDig]: {
    path: 'brick_animations',
    fileName: 'brick_dig',
    name: [ANIMATIONS.brickDig],
    end: 3,
    loop: false,
    frameRate: 15,
  },
  [ANIMATIONS.brickRecovery]: {
    path: 'brick_animations',
    fileName: 'brick_recovery',
    name: [ANIMATIONS.brickRecovery],
    end: 4,
    loop: false,
    frameRate: 10,
  },
};

export { ANIMATIONS, ANIMATIONS_CONFIG };
