const ANIMATIONS = {
  playerRunRight: {
    path: 'player',
    name: 'player_run_right',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  playerRunLeft: {
    path: 'player',
    name: 'player_run_left',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  playerLadderClimb: {
    path: 'player',
    name: 'player_ladder_climb',
    end: 2,
    loop: true,
    frameRate: 15,
  },
  playerRopeClimbLeft: {
    path: 'player',
    name: 'player_rope_climb_left',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  playerRopeClimbRight: {
    path: 'player',
    name: 'player_rope_climb_right',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  enemyRunRight: {
    path: 'enemy',
    name: 'enemy_run_right',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  enemyRunLeft: {
    path: 'enemy',
    name: 'enemy_run_left',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  enemyLadderClimb: {
    path: 'enemy',
    name: 'enemy_ladder_climb',
    end: 2,
    loop: true,
    frameRate: 15,
  },
  enemyRopeClimbLeft: {
    path: 'enemy',
    name: 'enemy_rope_climb_left',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  enemyRopeClimbRight: {
    path: 'enemy',
    name: 'enemy_rope_climb_right',
    end: 3,
    loop: true,
    frameRate: 15,
  },
  brickDig: {
    path: 'brick_animations',
    name: 'brick_dig',
    end: 3,
    loop: false,
    frameRate: 15,
  },
  brickRecovery: {
    path: 'brick_animations',
    name: 'brick_recovery',
    end: 4,
    loop: false,
    frameRate: 10,
  },
};

export default ANIMATIONS;
